import Head from "next/head";
import styles from "../styles/Home.module.css";
import GalleryCard from "../components/GalleryCard";
import Header from "../components/Header";
import data from "/data/landscapes.json";
import { Grid, Box } from "@mui/material";

export async function getStaticProps() {
  //This could be an API call instead of a file read.
  const allData = await data;

  return {
    props: {
      allData,
    },
  };
}

export default function Home({ allData }) {
  const albumData = allData.album;

  return (
    <div>
      <section className={styles.container}>
        <Head>
          <title>James Thomas Photo Gallery</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header
          img={allData.profile_picture}
          bio={allData.bio}
          name={allData.name}
          email={allData.email}
          picture={allData.profile_picture}
        />
      </section>
      <Box className={styles.main} sx={{ flexGrow: 1 }}>
        <Grid
          container
          spacing={{ xs: 2, md: 3 }}
          columns={{ xs: 4, sm: 8, md: 12 }}
        >
          {albumData.map((data) => (
            <Grid item xs={2} sm={4} md={4} key={data.id}>
            <GalleryCard
              key={data.id}
              img={data.img}
              date={data.date}
              title={data.title}
              featured={data.featured}
              description={data.description}
            />
            </Grid>
          ))}
        </Grid>
      </Box>
    </div>
  );
}
