import Head from "next/head";
import styles from "../styles/Home.module.css";
import Article from "../components/Article";
import Header from "../components/Header";
import data from "/data/landscapes.json";

export async function getStaticProps() {
  //may need to await data
  const allData = await data;

  return {
    props: {
      allData,
    },
  };
}

export default function Home({ allData }) {
  const albumData = allData.album;

  return (
    <div>
      <section className={styles.container}>
        <Head>
          <title>James Thomas Photo Gallery</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header 
          img={allData.profile_picture}
          bio={allData.bio}
          name={allData.name}
          email={allData.email}
          picture={allData.profile_picture}
          />
      </section>
      <main className={styles.main}>
        {albumData.map((data) => (
          <Article 
          key={data.id}
          img={data.img}
          date={data.date}
          title={data.title}
          featured={data.featured}
          description={data.description}
          />
        ))}
      </main>
    </div>
  );
}

{
  /* <main className={styles.main}>
<h1 className={styles.title}>
  Welcome to <a href="https://nextjs.org">Next.js!</a>
</h1>

<p className={styles.description}>
  Get started by editing{' '}
  <code className={styles.code}>pages/index.js</code>
</p>

<div className={styles.grid}>
  <a href="https://nextjs.org/docs" className={styles.card}>
    <h2>Documentation &rarr;</h2>
    <p>Find in-depth information about Next.js features and API.</p>
  </a>

  <a href="https://nextjs.org/learn" className={styles.card}>
    <h2>Learn &rarr;</h2>
    <p>Learn about Next.js in an interactive course with quizzes!</p>
  </a>

  <a
    href="https://github.com/vercel/next.js/tree/master/examples"
    className={styles.card}
  >
    <h2>Examples &rarr;</h2>
    <p>Discover and deploy boilerplate example Next.js projects.</p>
  </a>

  <a
    href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    className={styles.card}
  >
    <h2>Deploy &rarr;</h2>
    <p>
      Instantly deploy your Next.js site to a public URL with Vercel.
    </p>
  </a>
</div>
</main>

<footer className={styles.footer}>
<a
  href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
  target="_blank"
  rel="noopener noreferrer"
>
  Powered by{' '}
  <span className={styles.logo}>
    <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
  </span>
</a>
</footer> */
}
